### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by nolazybits** [diogok/restserver#1]
Hello, and thank you much for the hard work you have done!!!

I was wondering if you could maybe create a branch with the naming convention specified here
http://groups.google.com/group/php-standards/web/final-proposal
using namespaces.

I'm using an autoloader classes that loads the class on demand looking at their full path (ie \Diogok\Rest\Server where the class Server.php in the folder Diogok\Rest will be

`namespace Diogok\Rest;
class Server 
{
...
}`

Saves tons of include lines :)

I have myself change your package naming convetion to fit my need, i could send you the files if needed (they might be some revision old thought)

Thx a lot again

**Comment by diogok** [comment]
Hi, that's a nice idea I also had in mind for a while. I'll create the branch soon.

**Comment by nolazybits** [comment]
If you need some help let me know, as I have already modified the existing source (not the latest rev though) to use namesapces.

Thx again :)

**Comment by diogok** [comment]
Sure, that would be great, do you know from what commit is it?

I created the branch for namespaces, so we can work on it.

**Comment by nolazybits** [comment]
Cheers for this... Will try to do a push request by tomorrow if good with you.
